'use strict',

module.exports = {
  // packet types
  PACKET_CMD_REQUEST: 0,
  PACKET_CMD_RESPONSE: 1,
  PACKET_CMD_UNKNOWN: 2,
  PACKET_EVENT_REGISTER: 3,
  PACKET_EVENT_UNREGISTER: 4,
  PACKET_EVENT_CONFIRM: 5,
  PACKET_EVENT_UNKNOWN: 6,
  PACKET_EVENT: 7,

  // message elements types
  ELEMENT_SECTION_START: 1,
  ELEMENT_SECTION_END: 2,
  ELEMENT_KEY_VALUE: 3,
  ELEMENT_LIST_START: 4,
  ELEMENT_LIST_ITEM: 5,
  ELEMENT_LIST_END: 6,
};
